// console.log(Math.round(78.7))
// console.log(Math.round(78.3))
// console.log(Math.ceil(78.3))
// console.log(Math.ceil(78.7))
// console.log(Math.ceil(-78.3))
// console.log(Math.floor(78.3))
// console.log(Math.floor(78.7))
// console.log(Math.floor(-78.7))
// console.log(Math.trunc(78.3))
// console.log(Math.trunc(78.7))
// console.log(Math.trunc())
// console.log(Math.trunc(-78.3))
console.log(Math.sign(78.3))
console.log(Math.sign(78.7))
console.log(Math.sign(-78.3))
console.log(Math.sign(null))
console.log(Math.sign(0))